#!/bin/bash
cd /root
if [ ! -d "blog" ]; then
  git clone https://gitee.com/huyonger/blog.git
fi

cd blog
git clean -f
git checkout .
git pull
npm install
pip3 install -r requirements.txt
npm run webpack.build.production
pm2 startOrReload pm2.json

if [ -f "/etc/nginx/conf.d/blog.conf" ]; then
  rm /etc/nginx/conf.d/blog.conf
fi
ln -s /root/blog/nginx.conf /etc/nginx/conf.d/blog.conf
if [ -f "/etc/nginx/conf.d/blog_https.conf" ]; then
  rm /etc/nginx/conf.d/blog_https.conf
fi
ln -s /root/blog/nginx_https.conf /etc/nginx/conf.d/blog_https.conf
systemctl restart nginx
